pipeline:
  name: test remote pipeline input set
  identifier: test_remote_pipeline_input_set
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: df
        identifier: df
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: df
                  identifier: df
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
