pipeline:
  name: test rate limit 22
  identifier: test_rate_limit_22
  tags: {}
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  stages:
    - stage:
        name: asfd
        identifier: asfd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fsd
                  identifier: fsd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
